# R21 gate fixture writer (read-only on the stock corpus): the real entry prototypes of the two level-trigger modules R21
# moves to the engine writer (Intel P43 VaultAlarmTriggered, Sabotage P11 reactorDestroyedFunction), in the format of the R19
# fixture (RESEARCH/MISSIONS_R19_RAILJACK_ENGINE_OWNER_2026-10-02/tools/encounter_entry_protos.py).
# Usage: python trigger_entry_protos.py <bootstrapper>/RENOVICE_TOOLCHAIN/engine_params/fixtures/MissionsR21/trigger_entry_protos.txt
import sys, hashlib
from pathlib import Path
T = Path(r'C:\Users\Bartek\OneDrive\Dokumenter\Warframe RE PROJECT RENOVICE\repos\apps\ability-editor\RESEARCH\UNIVERSAL_MISSION_REGISTRY_2026-09-29\tools')
sys.path.insert(0, str(T))
import deluau  # noqa: E402
ST = Path(r'C:\Users\Bartek\OneDrive\Dokumenter\Warframe RE PROJECT RENOVICE\repos\toolchains\de-luau-toolchain\work\u44-rawhash-2026-09-29\stock')
lines = ['# R21 gate fixture: entry prototypes of the level-trigger modules owned at the writer in R21, from the 44.0.2 stock',
         '# bytecode (repos/toolchains/de-luau-toolchain/work/u44-rawhash-2026-09-29/stock). One line per prototype:',
         '# <stock content key> <module SHA-256> <prototype = bytecode id> <instruction words> <raw code bytes, hex>',
         '# Generated by the ability editor record RESEARCH/MISSIONS_R21_PARAM_LANE_AUDIT_2026-10-02 (read-only).']
for f, key, p in [('Lotus_Scripts_Intel.lua_B', 'ee15b583788c3e7d', 43),
                  ('Lotus_Scripts_Sabotage.lua_B', '7e0adf2d83f7a086', 11)]:
    raw = (ST / f).read_bytes()
    assert deluau.body_key(raw) == key
    ins, _ = deluau.Module(raw).protos[p]
    start, end = ins[0][0], ins[-1][0] + len(ins[-1][1])
    code = raw[start:end]
    lines.append(f'{key} {hashlib.sha256(raw).hexdigest()} {p} {len(code) // 4} {code.hex()}')
Path(sys.argv[1]).write_text('\n'.join(lines) + '\n', encoding='ascii', newline='\n')
print('ok', len(lines))
