import sys, hashlib
from pathlib import Path
T = Path(r'C:\Users\Bartek\OneDrive\Dokumenter\Warframe RE PROJECT RENOVICE\repos\apps\ability-editor\RESEARCH\UNIVERSAL_MISSION_REGISTRY_2026-09-29\tools')
sys.path.insert(0, str(T))
import deluau
ST = Path(r'C:\Users\Bartek\OneDrive\Dokumenter\Warframe RE PROJECT RENOVICE\repos\toolchains\de-luau-toolchain\work\u44-rawhash-2026-09-29\stock')
lines = ['# R19 gate fixture: entry prototypes of the Railjack encounter modules, from the 44.0.2 stock bytecode',
         '# (repos/toolchains/de-luau-toolchain/work/u44-rawhash-2026-09-29/stock). One line per prototype:',
         '# <stock content key> <module SHA-256> <prototype = bytecode id> <instruction words> <raw code bytes, hex>',
         '# Generated by the ability editor record RESEARCH/MISSIONS_R19_RAILJACK_ENGINE_OWNER_2026-10-02 (read-only).']
for f, key, p in [('Lotus_Scripts_CrewShip_Encounters_KillFightersExterminateEncounter.lua_B', 'feb4ca192ef69f0a', 9),
                  ('Lotus_Scripts_CrewShip_Encounters_KillCrewShipsExterminateObjective.lua_B', 'e773280ca7743441', 9),
                  ('Lotus_Scripts_CrewShip_Encounters_BasicRailJackPatrol.lua_B', '0a6394a10884c38a', 15)]:
    raw = (ST / f).read_bytes()
    assert deluau.body_key(raw) == key
    ins, _ = deluau.Module(raw).protos[p]
    start, end = ins[0][0], ins[-1][0] + len(ins[-1][1])
    code = raw[start:end]
    lines.append(f'{key} {hashlib.sha256(raw).hexdigest()} {p} {len(code) // 4} {code.hex()}')
Path(sys.argv[1]).write_text('\n'.join(lines) + '\n', encoding='ascii', newline='\n')
print('ok', len(lines))
